//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("dbCajaModel", "FK_Caja_Usuarios", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProyectoDap3.Usuario), "Caja", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProyectoDap3.Caja), true)]
[assembly: EdmRelationshipAttribute("dbCajaModel", "FK_Dotacion_Caja", "Caja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProyectoDap3.Caja), "Dotacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProyectoDap3.Dotacion), true)]
[assembly: EdmRelationshipAttribute("dbCajaModel", "FK_EgresoCaja_Caja", "Caja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProyectoDap3.Caja), "EgresoCaja", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProyectoDap3.EgresoCaja), true)]
[assembly: EdmRelationshipAttribute("dbCajaModel", "FK_IngresoCaja_Caja", "Caja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProyectoDap3.Caja), "IngresoCaja", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProyectoDap3.IngresoCaja), true)]
[assembly: EdmRelationshipAttribute("dbCajaModel", "FK_Personas_Cargos", "Cargos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProyectoDap3.Cargo), "Personas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProyectoDap3.Persona), true)]
[assembly: EdmRelationshipAttribute("dbCajaModel", "FK_IngresoCaja_CxC", "CxC", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProyectoDap3.CxC), "IngresoCaja", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProyectoDap3.IngresoCaja), true)]
[assembly: EdmRelationshipAttribute("dbCajaModel", "FK_DetallesEgreso_EgresoCaja", "EgresoCaja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProyectoDap3.EgresoCaja), "DetallesEgreso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProyectoDap3.DetallesEgreso), true)]
[assembly: EdmRelationshipAttribute("dbCajaModel", "FK_Usuarios_Personas", "Personas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProyectoDap3.Persona), "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProyectoDap3.Usuario), true)]

#endregion

namespace ProyectoDap3
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class dbCajaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto dbCajaEntities usando la cadena de conexión encontrada en la sección 'dbCajaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public dbCajaEntities() : base("name=dbCajaEntities", "dbCajaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto dbCajaEntities.
        /// </summary>
        public dbCajaEntities(string connectionString) : base(connectionString, "dbCajaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto dbCajaEntities.
        /// </summary>
        public dbCajaEntities(EntityConnection connection) : base(connection, "dbCajaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Caja> Cajas
        {
            get
            {
                if ((_Cajas == null))
                {
                    _Cajas = base.CreateObjectSet<Caja>("Cajas");
                }
                return _Cajas;
            }
        }
        private ObjectSet<Caja> _Cajas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cargo> Cargos
        {
            get
            {
                if ((_Cargos == null))
                {
                    _Cargos = base.CreateObjectSet<Cargo>("Cargos");
                }
                return _Cargos;
            }
        }
        private ObjectSet<Cargo> _Cargos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CxC> CxCs
        {
            get
            {
                if ((_CxCs == null))
                {
                    _CxCs = base.CreateObjectSet<CxC>("CxCs");
                }
                return _CxCs;
            }
        }
        private ObjectSet<CxC> _CxCs;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DetallesEgreso> DetallesEgresoes
        {
            get
            {
                if ((_DetallesEgresoes == null))
                {
                    _DetallesEgresoes = base.CreateObjectSet<DetallesEgreso>("DetallesEgresoes");
                }
                return _DetallesEgresoes;
            }
        }
        private ObjectSet<DetallesEgreso> _DetallesEgresoes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Dotacion> Dotacions
        {
            get
            {
                if ((_Dotacions == null))
                {
                    _Dotacions = base.CreateObjectSet<Dotacion>("Dotacions");
                }
                return _Dotacions;
            }
        }
        private ObjectSet<Dotacion> _Dotacions;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EgresoCaja> EgresoCajas
        {
            get
            {
                if ((_EgresoCajas == null))
                {
                    _EgresoCajas = base.CreateObjectSet<EgresoCaja>("EgresoCajas");
                }
                return _EgresoCajas;
            }
        }
        private ObjectSet<EgresoCaja> _EgresoCajas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<IngresoCaja> IngresoCajas
        {
            get
            {
                if ((_IngresoCajas == null))
                {
                    _IngresoCajas = base.CreateObjectSet<IngresoCaja>("IngresoCajas");
                }
                return _IngresoCajas;
            }
        }
        private ObjectSet<IngresoCaja> _IngresoCajas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Persona> Personas
        {
            get
            {
                if ((_Personas == null))
                {
                    _Personas = base.CreateObjectSet<Persona>("Personas");
                }
                return _Personas;
            }
        }
        private ObjectSet<Persona> _Personas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipoCambioDolar> TipoCambioDolars
        {
            get
            {
                if ((_TipoCambioDolars == null))
                {
                    _TipoCambioDolars = base.CreateObjectSet<TipoCambioDolar>("TipoCambioDolars");
                }
                return _TipoCambioDolars;
            }
        }
        private ObjectSet<TipoCambioDolar> _TipoCambioDolars;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cajas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCajas(Caja caja)
        {
            base.AddObject("Cajas", caja);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cargos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCargos(Cargo cargo)
        {
            base.AddObject("Cargos", cargo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CxCs. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCxCs(CxC cxC)
        {
            base.AddObject("CxCs", cxC);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DetallesEgresoes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDetallesEgresoes(DetallesEgreso detallesEgreso)
        {
            base.AddObject("DetallesEgresoes", detallesEgreso);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Dotacions. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDotacions(Dotacion dotacion)
        {
            base.AddObject("Dotacions", dotacion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EgresoCajas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEgresoCajas(EgresoCaja egresoCaja)
        {
            base.AddObject("EgresoCajas", egresoCaja);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet IngresoCajas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToIngresoCajas(IngresoCaja ingresoCaja)
        {
            base.AddObject("IngresoCajas", ingresoCaja);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Personas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPersonas(Persona persona)
        {
            base.AddObject("Personas", persona);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TipoCambioDolars. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTipoCambioDolars(TipoCambioDolar tipoCambioDolar)
        {
            base.AddObject("TipoCambioDolars", tipoCambioDolar);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="Caja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Caja : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Caja.
        /// </summary>
        /// <param name="idCaja">Valor inicial de la propiedad idCaja.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="fechahoraapertura">Valor inicial de la propiedad fechahoraapertura.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        public static Caja CreateCaja(global::System.Int32 idCaja, global::System.String estado, global::System.DateTime fechahoraapertura, global::System.Int32 usuario)
        {
            Caja caja = new Caja();
            caja.idCaja = idCaja;
            caja.estado = estado;
            caja.fechahoraapertura = fechahoraapertura;
            caja.usuario = usuario;
            return caja;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCaja
        {
            get
            {
                return _idCaja;
            }
            set
            {
                if (_idCaja != value)
                {
                    OnidCajaChanging(value);
                    ReportPropertyChanging("idCaja");
                    _idCaja = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCaja");
                    OnidCajaChanged();
                }
            }
        }
        private global::System.Int32 _idCaja;
        partial void OnidCajaChanging(global::System.Int32 value);
        partial void OnidCajaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechahoraapertura
        {
            get
            {
                return _fechahoraapertura;
            }
            set
            {
                OnfechahoraaperturaChanging(value);
                ReportPropertyChanging("fechahoraapertura");
                _fechahoraapertura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechahoraapertura");
                OnfechahoraaperturaChanged();
            }
        }
        private global::System.DateTime _fechahoraapertura;
        partial void OnfechahoraaperturaChanging(global::System.DateTime value);
        partial void OnfechahoraaperturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.Int32 _usuario;
        partial void OnusuarioChanging(global::System.Int32 value);
        partial void OnusuarioChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_Caja_Usuarios", "Usuarios")]
        public Usuario Usuario1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("dbCajaModel.FK_Caja_Usuarios", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("dbCajaModel.FK_Caja_Usuarios", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> Usuario1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("dbCajaModel.FK_Caja_Usuarios", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("dbCajaModel.FK_Caja_Usuarios", "Usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_Dotacion_Caja", "Dotacion")]
        public EntityCollection<Dotacion> Dotacions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Dotacion>("dbCajaModel.FK_Dotacion_Caja", "Dotacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Dotacion>("dbCajaModel.FK_Dotacion_Caja", "Dotacion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_EgresoCaja_Caja", "EgresoCaja")]
        public EntityCollection<EgresoCaja> EgresoCajas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EgresoCaja>("dbCajaModel.FK_EgresoCaja_Caja", "EgresoCaja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EgresoCaja>("dbCajaModel.FK_EgresoCaja_Caja", "EgresoCaja", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_IngresoCaja_Caja", "IngresoCaja")]
        public EntityCollection<IngresoCaja> IngresoCajas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IngresoCaja>("dbCajaModel.FK_IngresoCaja_Caja", "IngresoCaja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IngresoCaja>("dbCajaModel.FK_IngresoCaja_Caja", "IngresoCaja", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="Cargo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cargo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cargo.
        /// </summary>
        /// <param name="idCargo">Valor inicial de la propiedad idCargo.</param>
        /// <param name="cargo1">Valor inicial de la propiedad Cargo1.</param>
        public static Cargo CreateCargo(global::System.Int32 idCargo, global::System.String cargo1)
        {
            Cargo cargo = new Cargo();
            cargo.idCargo = idCargo;
            cargo.Cargo1 = cargo1;
            return cargo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCargo
        {
            get
            {
                return _idCargo;
            }
            set
            {
                if (_idCargo != value)
                {
                    OnidCargoChanging(value);
                    ReportPropertyChanging("idCargo");
                    _idCargo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCargo");
                    OnidCargoChanged();
                }
            }
        }
        private global::System.Int32 _idCargo;
        partial void OnidCargoChanging(global::System.Int32 value);
        partial void OnidCargoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cargo1
        {
            get
            {
                return _Cargo1;
            }
            set
            {
                OnCargo1Changing(value);
                ReportPropertyChanging("Cargo1");
                _Cargo1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cargo1");
                OnCargo1Changed();
            }
        }
        private global::System.String _Cargo1;
        partial void OnCargo1Changing(global::System.String value);
        partial void OnCargo1Changed();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_Personas_Cargos", "Personas")]
        public EntityCollection<Persona> Personas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Persona>("dbCajaModel.FK_Personas_Cargos", "Personas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Persona>("dbCajaModel.FK_Personas_Cargos", "Personas", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="CxC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CxC : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CxC.
        /// </summary>
        /// <param name="idCxC">Valor inicial de la propiedad idCxC.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="fechahora">Valor inicial de la propiedad fechahora.</param>
        /// <param name="montoPagar">Valor inicial de la propiedad montoPagar.</param>
        public static CxC CreateCxC(global::System.Int32 idCxC, global::System.String estado, global::System.DateTime fechahora, global::System.Decimal montoPagar)
        {
            CxC cxC = new CxC();
            cxC.idCxC = idCxC;
            cxC.estado = estado;
            cxC.fechahora = fechahora;
            cxC.montoPagar = montoPagar;
            return cxC;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCxC
        {
            get
            {
                return _idCxC;
            }
            set
            {
                if (_idCxC != value)
                {
                    OnidCxCChanging(value);
                    ReportPropertyChanging("idCxC");
                    _idCxC = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idCxC");
                    OnidCxCChanged();
                }
            }
        }
        private global::System.Int32 _idCxC;
        partial void OnidCxCChanging(global::System.Int32 value);
        partial void OnidCxCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechahora
        {
            get
            {
                return _fechahora;
            }
            set
            {
                OnfechahoraChanging(value);
                ReportPropertyChanging("fechahora");
                _fechahora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechahora");
                OnfechahoraChanged();
            }
        }
        private global::System.DateTime _fechahora;
        partial void OnfechahoraChanging(global::System.DateTime value);
        partial void OnfechahoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal montoPagar
        {
            get
            {
                return _montoPagar;
            }
            set
            {
                OnmontoPagarChanging(value);
                ReportPropertyChanging("montoPagar");
                _montoPagar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("montoPagar");
                OnmontoPagarChanged();
            }
        }
        private global::System.Decimal _montoPagar;
        partial void OnmontoPagarChanging(global::System.Decimal value);
        partial void OnmontoPagarChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_IngresoCaja_CxC", "IngresoCaja")]
        public EntityCollection<IngresoCaja> IngresoCajas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IngresoCaja>("dbCajaModel.FK_IngresoCaja_CxC", "IngresoCaja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IngresoCaja>("dbCajaModel.FK_IngresoCaja_CxC", "IngresoCaja", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="DetallesEgreso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetallesEgreso : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DetallesEgreso.
        /// </summary>
        /// <param name="idDetEgreso">Valor inicial de la propiedad idDetEgreso.</param>
        /// <param name="idEgreso">Valor inicial de la propiedad IdEgreso.</param>
        /// <param name="c200bs">Valor inicial de la propiedad c200bs.</param>
        /// <param name="c100bs">Valor inicial de la propiedad c100bs.</param>
        /// <param name="c50bs">Valor inicial de la propiedad c50bs.</param>
        /// <param name="c100dolares">Valor inicial de la propiedad c100dolares.</param>
        /// <param name="c50dolares">Valor inicial de la propiedad c50dolares.</param>
        /// <param name="c20dolares">Valor inicial de la propiedad c20dolares.</param>
        /// <param name="c10dolares">Valor inicial de la propiedad c10dolares.</param>
        /// <param name="c5dolares">Valor inicial de la propiedad c5dolares.</param>
        /// <param name="c1dolares">Valor inicial de la propiedad c1dolares.</param>
        /// <param name="tCambio">Valor inicial de la propiedad TCambio.</param>
        public static DetallesEgreso CreateDetallesEgreso(global::System.Int32 idDetEgreso, global::System.Int32 idEgreso, global::System.Int32 c200bs, global::System.Int32 c100bs, global::System.Int32 c50bs, global::System.Int32 c100dolares, global::System.Int32 c50dolares, global::System.Int32 c20dolares, global::System.Int32 c10dolares, global::System.Int32 c5dolares, global::System.Int32 c1dolares, global::System.Decimal tCambio)
        {
            DetallesEgreso detallesEgreso = new DetallesEgreso();
            detallesEgreso.idDetEgreso = idDetEgreso;
            detallesEgreso.IdEgreso = idEgreso;
            detallesEgreso.c200bs = c200bs;
            detallesEgreso.c100bs = c100bs;
            detallesEgreso.c50bs = c50bs;
            detallesEgreso.c100dolares = c100dolares;
            detallesEgreso.c50dolares = c50dolares;
            detallesEgreso.c20dolares = c20dolares;
            detallesEgreso.c10dolares = c10dolares;
            detallesEgreso.c5dolares = c5dolares;
            detallesEgreso.c1dolares = c1dolares;
            detallesEgreso.TCambio = tCambio;
            return detallesEgreso;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDetEgreso
        {
            get
            {
                return _idDetEgreso;
            }
            set
            {
                if (_idDetEgreso != value)
                {
                    OnidDetEgresoChanging(value);
                    ReportPropertyChanging("idDetEgreso");
                    _idDetEgreso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDetEgreso");
                    OnidDetEgresoChanged();
                }
            }
        }
        private global::System.Int32 _idDetEgreso;
        partial void OnidDetEgresoChanging(global::System.Int32 value);
        partial void OnidDetEgresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEgreso
        {
            get
            {
                return _IdEgreso;
            }
            set
            {
                OnIdEgresoChanging(value);
                ReportPropertyChanging("IdEgreso");
                _IdEgreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEgreso");
                OnIdEgresoChanged();
            }
        }
        private global::System.Int32 _IdEgreso;
        partial void OnIdEgresoChanging(global::System.Int32 value);
        partial void OnIdEgresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c200bs
        {
            get
            {
                return _c200bs;
            }
            set
            {
                Onc200bsChanging(value);
                ReportPropertyChanging("c200bs");
                _c200bs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c200bs");
                Onc200bsChanged();
            }
        }
        private global::System.Int32 _c200bs;
        partial void Onc200bsChanging(global::System.Int32 value);
        partial void Onc200bsChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c100bs
        {
            get
            {
                return _c100bs;
            }
            set
            {
                Onc100bsChanging(value);
                ReportPropertyChanging("c100bs");
                _c100bs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c100bs");
                Onc100bsChanged();
            }
        }
        private global::System.Int32 _c100bs;
        partial void Onc100bsChanging(global::System.Int32 value);
        partial void Onc100bsChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c50bs
        {
            get
            {
                return _c50bs;
            }
            set
            {
                Onc50bsChanging(value);
                ReportPropertyChanging("c50bs");
                _c50bs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c50bs");
                Onc50bsChanged();
            }
        }
        private global::System.Int32 _c50bs;
        partial void Onc50bsChanging(global::System.Int32 value);
        partial void Onc50bsChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c100dolares
        {
            get
            {
                return _c100dolares;
            }
            set
            {
                Onc100dolaresChanging(value);
                ReportPropertyChanging("c100dolares");
                _c100dolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c100dolares");
                Onc100dolaresChanged();
            }
        }
        private global::System.Int32 _c100dolares;
        partial void Onc100dolaresChanging(global::System.Int32 value);
        partial void Onc100dolaresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c50dolares
        {
            get
            {
                return _c50dolares;
            }
            set
            {
                Onc50dolaresChanging(value);
                ReportPropertyChanging("c50dolares");
                _c50dolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c50dolares");
                Onc50dolaresChanged();
            }
        }
        private global::System.Int32 _c50dolares;
        partial void Onc50dolaresChanging(global::System.Int32 value);
        partial void Onc50dolaresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c20dolares
        {
            get
            {
                return _c20dolares;
            }
            set
            {
                Onc20dolaresChanging(value);
                ReportPropertyChanging("c20dolares");
                _c20dolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c20dolares");
                Onc20dolaresChanged();
            }
        }
        private global::System.Int32 _c20dolares;
        partial void Onc20dolaresChanging(global::System.Int32 value);
        partial void Onc20dolaresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c10dolares
        {
            get
            {
                return _c10dolares;
            }
            set
            {
                Onc10dolaresChanging(value);
                ReportPropertyChanging("c10dolares");
                _c10dolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c10dolares");
                Onc10dolaresChanged();
            }
        }
        private global::System.Int32 _c10dolares;
        partial void Onc10dolaresChanging(global::System.Int32 value);
        partial void Onc10dolaresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c5dolares
        {
            get
            {
                return _c5dolares;
            }
            set
            {
                Onc5dolaresChanging(value);
                ReportPropertyChanging("c5dolares");
                _c5dolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c5dolares");
                Onc5dolaresChanged();
            }
        }
        private global::System.Int32 _c5dolares;
        partial void Onc5dolaresChanging(global::System.Int32 value);
        partial void Onc5dolaresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 c1dolares
        {
            get
            {
                return _c1dolares;
            }
            set
            {
                Onc1dolaresChanging(value);
                ReportPropertyChanging("c1dolares");
                _c1dolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("c1dolares");
                Onc1dolaresChanged();
            }
        }
        private global::System.Int32 _c1dolares;
        partial void Onc1dolaresChanging(global::System.Int32 value);
        partial void Onc1dolaresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TCambio
        {
            get
            {
                return _TCambio;
            }
            set
            {
                OnTCambioChanging(value);
                ReportPropertyChanging("TCambio");
                _TCambio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TCambio");
                OnTCambioChanged();
            }
        }
        private global::System.Decimal _TCambio;
        partial void OnTCambioChanging(global::System.Decimal value);
        partial void OnTCambioChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_DetallesEgreso_EgresoCaja", "EgresoCaja")]
        public EgresoCaja EgresoCaja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EgresoCaja>("dbCajaModel.FK_DetallesEgreso_EgresoCaja", "EgresoCaja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EgresoCaja>("dbCajaModel.FK_DetallesEgreso_EgresoCaja", "EgresoCaja").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EgresoCaja> EgresoCajaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EgresoCaja>("dbCajaModel.FK_DetallesEgreso_EgresoCaja", "EgresoCaja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EgresoCaja>("dbCajaModel.FK_DetallesEgreso_EgresoCaja", "EgresoCaja", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="Dotacion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dotacion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Dotacion.
        /// </summary>
        /// <param name="idDotacion">Valor inicial de la propiedad idDotacion.</param>
        /// <param name="caja">Valor inicial de la propiedad caja.</param>
        /// <param name="efectivo">Valor inicial de la propiedad efectivo.</param>
        /// <param name="recibido">Valor inicial de la propiedad recibido.</param>
        /// <param name="entregado">Valor inicial de la propiedad entregado.</param>
        public static Dotacion CreateDotacion(global::System.Int32 idDotacion, global::System.Int32 caja, global::System.Decimal efectivo, global::System.Decimal recibido, global::System.Decimal entregado)
        {
            Dotacion dotacion = new Dotacion();
            dotacion.idDotacion = idDotacion;
            dotacion.caja = caja;
            dotacion.efectivo = efectivo;
            dotacion.recibido = recibido;
            dotacion.entregado = entregado;
            return dotacion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idDotacion
        {
            get
            {
                return _idDotacion;
            }
            set
            {
                if (_idDotacion != value)
                {
                    OnidDotacionChanging(value);
                    ReportPropertyChanging("idDotacion");
                    _idDotacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idDotacion");
                    OnidDotacionChanged();
                }
            }
        }
        private global::System.Int32 _idDotacion;
        partial void OnidDotacionChanging(global::System.Int32 value);
        partial void OnidDotacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 caja
        {
            get
            {
                return _caja;
            }
            set
            {
                OncajaChanging(value);
                ReportPropertyChanging("caja");
                _caja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("caja");
                OncajaChanged();
            }
        }
        private global::System.Int32 _caja;
        partial void OncajaChanging(global::System.Int32 value);
        partial void OncajaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal efectivo
        {
            get
            {
                return _efectivo;
            }
            set
            {
                OnefectivoChanging(value);
                ReportPropertyChanging("efectivo");
                _efectivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("efectivo");
                OnefectivoChanged();
            }
        }
        private global::System.Decimal _efectivo;
        partial void OnefectivoChanging(global::System.Decimal value);
        partial void OnefectivoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal recibido
        {
            get
            {
                return _recibido;
            }
            set
            {
                OnrecibidoChanging(value);
                ReportPropertyChanging("recibido");
                _recibido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recibido");
                OnrecibidoChanged();
            }
        }
        private global::System.Decimal _recibido;
        partial void OnrecibidoChanging(global::System.Decimal value);
        partial void OnrecibidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal entregado
        {
            get
            {
                return _entregado;
            }
            set
            {
                OnentregadoChanging(value);
                ReportPropertyChanging("entregado");
                _entregado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entregado");
                OnentregadoChanged();
            }
        }
        private global::System.Decimal _entregado;
        partial void OnentregadoChanging(global::System.Decimal value);
        partial void OnentregadoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_Dotacion_Caja", "Caja")]
        public Caja Caja1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_Dotacion_Caja", "Caja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_Dotacion_Caja", "Caja").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Caja> Caja1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_Dotacion_Caja", "Caja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Caja>("dbCajaModel.FK_Dotacion_Caja", "Caja", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="EgresoCaja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EgresoCaja : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EgresoCaja.
        /// </summary>
        /// <param name="idEgreso">Valor inicial de la propiedad idEgreso.</param>
        /// <param name="idCaja">Valor inicial de la propiedad idCaja.</param>
        /// <param name="montoEgreso">Valor inicial de la propiedad MontoEgreso.</param>
        public static EgresoCaja CreateEgresoCaja(global::System.Int32 idEgreso, global::System.Int32 idCaja, global::System.Decimal montoEgreso)
        {
            EgresoCaja egresoCaja = new EgresoCaja();
            egresoCaja.idEgreso = idEgreso;
            egresoCaja.idCaja = idCaja;
            egresoCaja.MontoEgreso = montoEgreso;
            return egresoCaja;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEgreso
        {
            get
            {
                return _idEgreso;
            }
            set
            {
                if (_idEgreso != value)
                {
                    OnidEgresoChanging(value);
                    ReportPropertyChanging("idEgreso");
                    _idEgreso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEgreso");
                    OnidEgresoChanged();
                }
            }
        }
        private global::System.Int32 _idEgreso;
        partial void OnidEgresoChanging(global::System.Int32 value);
        partial void OnidEgresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCaja
        {
            get
            {
                return _idCaja;
            }
            set
            {
                OnidCajaChanging(value);
                ReportPropertyChanging("idCaja");
                _idCaja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCaja");
                OnidCajaChanged();
            }
        }
        private global::System.Int32 _idCaja;
        partial void OnidCajaChanging(global::System.Int32 value);
        partial void OnidCajaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MontoEgreso
        {
            get
            {
                return _MontoEgreso;
            }
            set
            {
                OnMontoEgresoChanging(value);
                ReportPropertyChanging("MontoEgreso");
                _MontoEgreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoEgreso");
                OnMontoEgresoChanged();
            }
        }
        private global::System.Decimal _MontoEgreso;
        partial void OnMontoEgresoChanging(global::System.Decimal value);
        partial void OnMontoEgresoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_EgresoCaja_Caja", "Caja")]
        public Caja Caja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_EgresoCaja_Caja", "Caja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_EgresoCaja_Caja", "Caja").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Caja> CajaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_EgresoCaja_Caja", "Caja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Caja>("dbCajaModel.FK_EgresoCaja_Caja", "Caja", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_DetallesEgreso_EgresoCaja", "DetallesEgreso")]
        public EntityCollection<DetallesEgreso> DetallesEgresoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetallesEgreso>("dbCajaModel.FK_DetallesEgreso_EgresoCaja", "DetallesEgreso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetallesEgreso>("dbCajaModel.FK_DetallesEgreso_EgresoCaja", "DetallesEgreso", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="IngresoCaja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IngresoCaja : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto IngresoCaja.
        /// </summary>
        /// <param name="idIngreso">Valor inicial de la propiedad idIngreso.</param>
        /// <param name="idCxC">Valor inicial de la propiedad idCxC.</param>
        /// <param name="idCaja">Valor inicial de la propiedad idCaja.</param>
        /// <param name="bs">Valor inicial de la propiedad bs.</param>
        /// <param name="dolares">Valor inicial de la propiedad dolares.</param>
        /// <param name="bolivianosTCambio">Valor inicial de la propiedad bolivianosTCambio.</param>
        /// <param name="visa">Valor inicial de la propiedad visa.</param>
        /// <param name="master">Valor inicial de la propiedad master.</param>
        /// <param name="promocion">Valor inicial de la propiedad promocion.</param>
        /// <param name="tCambio">Valor inicial de la propiedad TCambio.</param>
        public static IngresoCaja CreateIngresoCaja(global::System.Int32 idIngreso, global::System.Int32 idCxC, global::System.Int32 idCaja, global::System.Decimal bs, global::System.Decimal dolares, global::System.Decimal bolivianosTCambio, global::System.Decimal visa, global::System.Decimal master, global::System.Decimal promocion, global::System.Decimal tCambio)
        {
            IngresoCaja ingresoCaja = new IngresoCaja();
            ingresoCaja.idIngreso = idIngreso;
            ingresoCaja.idCxC = idCxC;
            ingresoCaja.idCaja = idCaja;
            ingresoCaja.bs = bs;
            ingresoCaja.dolares = dolares;
            ingresoCaja.bolivianosTCambio = bolivianosTCambio;
            ingresoCaja.visa = visa;
            ingresoCaja.master = master;
            ingresoCaja.promocion = promocion;
            ingresoCaja.TCambio = tCambio;
            return ingresoCaja;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idIngreso
        {
            get
            {
                return _idIngreso;
            }
            set
            {
                if (_idIngreso != value)
                {
                    OnidIngresoChanging(value);
                    ReportPropertyChanging("idIngreso");
                    _idIngreso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idIngreso");
                    OnidIngresoChanged();
                }
            }
        }
        private global::System.Int32 _idIngreso;
        partial void OnidIngresoChanging(global::System.Int32 value);
        partial void OnidIngresoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCxC
        {
            get
            {
                return _idCxC;
            }
            set
            {
                OnidCxCChanging(value);
                ReportPropertyChanging("idCxC");
                _idCxC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCxC");
                OnidCxCChanged();
            }
        }
        private global::System.Int32 _idCxC;
        partial void OnidCxCChanging(global::System.Int32 value);
        partial void OnidCxCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCaja
        {
            get
            {
                return _idCaja;
            }
            set
            {
                OnidCajaChanging(value);
                ReportPropertyChanging("idCaja");
                _idCaja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCaja");
                OnidCajaChanged();
            }
        }
        private global::System.Int32 _idCaja;
        partial void OnidCajaChanging(global::System.Int32 value);
        partial void OnidCajaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal bs
        {
            get
            {
                return _bs;
            }
            set
            {
                OnbsChanging(value);
                ReportPropertyChanging("bs");
                _bs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bs");
                OnbsChanged();
            }
        }
        private global::System.Decimal _bs;
        partial void OnbsChanging(global::System.Decimal value);
        partial void OnbsChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal dolares
        {
            get
            {
                return _dolares;
            }
            set
            {
                OndolaresChanging(value);
                ReportPropertyChanging("dolares");
                _dolares = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dolares");
                OndolaresChanged();
            }
        }
        private global::System.Decimal _dolares;
        partial void OndolaresChanging(global::System.Decimal value);
        partial void OndolaresChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal bolivianosTCambio
        {
            get
            {
                return _bolivianosTCambio;
            }
            set
            {
                OnbolivianosTCambioChanging(value);
                ReportPropertyChanging("bolivianosTCambio");
                _bolivianosTCambio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bolivianosTCambio");
                OnbolivianosTCambioChanged();
            }
        }
        private global::System.Decimal _bolivianosTCambio;
        partial void OnbolivianosTCambioChanging(global::System.Decimal value);
        partial void OnbolivianosTCambioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal visa
        {
            get
            {
                return _visa;
            }
            set
            {
                OnvisaChanging(value);
                ReportPropertyChanging("visa");
                _visa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("visa");
                OnvisaChanged();
            }
        }
        private global::System.Decimal _visa;
        partial void OnvisaChanging(global::System.Decimal value);
        partial void OnvisaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal master
        {
            get
            {
                return _master;
            }
            set
            {
                OnmasterChanging(value);
                ReportPropertyChanging("master");
                _master = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("master");
                OnmasterChanged();
            }
        }
        private global::System.Decimal _master;
        partial void OnmasterChanging(global::System.Decimal value);
        partial void OnmasterChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal promocion
        {
            get
            {
                return _promocion;
            }
            set
            {
                OnpromocionChanging(value);
                ReportPropertyChanging("promocion");
                _promocion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("promocion");
                OnpromocionChanged();
            }
        }
        private global::System.Decimal _promocion;
        partial void OnpromocionChanging(global::System.Decimal value);
        partial void OnpromocionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TCambio
        {
            get
            {
                return _TCambio;
            }
            set
            {
                OnTCambioChanging(value);
                ReportPropertyChanging("TCambio");
                _TCambio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TCambio");
                OnTCambioChanged();
            }
        }
        private global::System.Decimal _TCambio;
        partial void OnTCambioChanging(global::System.Decimal value);
        partial void OnTCambioChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_IngresoCaja_Caja", "Caja")]
        public Caja Caja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_IngresoCaja_Caja", "Caja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_IngresoCaja_Caja", "Caja").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Caja> CajaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caja>("dbCajaModel.FK_IngresoCaja_Caja", "Caja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Caja>("dbCajaModel.FK_IngresoCaja_Caja", "Caja", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_IngresoCaja_CxC", "CxC")]
        public CxC CxC
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CxC>("dbCajaModel.FK_IngresoCaja_CxC", "CxC").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CxC>("dbCajaModel.FK_IngresoCaja_CxC", "CxC").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CxC> CxCReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CxC>("dbCajaModel.FK_IngresoCaja_CxC", "CxC");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CxC>("dbCajaModel.FK_IngresoCaja_CxC", "CxC", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Persona : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Persona.
        /// </summary>
        /// <param name="idPersona">Valor inicial de la propiedad idPersona.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="app">Valor inicial de la propiedad app.</param>
        /// <param name="apm">Valor inicial de la propiedad apm.</param>
        /// <param name="cargo">Valor inicial de la propiedad cargo.</param>
        public static Persona CreatePersona(global::System.Int32 idPersona, global::System.String nombre, global::System.String app, global::System.String apm, global::System.Int32 cargo)
        {
            Persona persona = new Persona();
            persona.idPersona = idPersona;
            persona.nombre = nombre;
            persona.app = app;
            persona.apm = apm;
            persona.cargo = cargo;
            return persona;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPersona
        {
            get
            {
                return _idPersona;
            }
            set
            {
                if (_idPersona != value)
                {
                    OnidPersonaChanging(value);
                    ReportPropertyChanging("idPersona");
                    _idPersona = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPersona");
                    OnidPersonaChanged();
                }
            }
        }
        private global::System.Int32 _idPersona;
        partial void OnidPersonaChanging(global::System.Int32 value);
        partial void OnidPersonaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String app
        {
            get
            {
                return _app;
            }
            set
            {
                OnappChanging(value);
                ReportPropertyChanging("app");
                _app = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("app");
                OnappChanged();
            }
        }
        private global::System.String _app;
        partial void OnappChanging(global::System.String value);
        partial void OnappChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apm
        {
            get
            {
                return _apm;
            }
            set
            {
                OnapmChanging(value);
                ReportPropertyChanging("apm");
                _apm = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apm");
                OnapmChanged();
            }
        }
        private global::System.String _apm;
        partial void OnapmChanging(global::System.String value);
        partial void OnapmChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cargo
        {
            get
            {
                return _cargo;
            }
            set
            {
                OncargoChanging(value);
                ReportPropertyChanging("cargo");
                _cargo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cargo");
                OncargoChanged();
            }
        }
        private global::System.Int32 _cargo;
        partial void OncargoChanging(global::System.Int32 value);
        partial void OncargoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_Personas_Cargos", "Cargos")]
        public Cargo Cargo1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("dbCajaModel.FK_Personas_Cargos", "Cargos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("dbCajaModel.FK_Personas_Cargos", "Cargos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cargo> Cargo1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cargo>("dbCajaModel.FK_Personas_Cargos", "Cargos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cargo>("dbCajaModel.FK_Personas_Cargos", "Cargos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_Usuarios_Personas", "Usuarios")]
        public EntityCollection<Usuario> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("dbCajaModel.FK_Usuarios_Personas", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("dbCajaModel.FK_Usuarios_Personas", "Usuarios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="TipoCambioDolar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoCambioDolar : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipoCambioDolar.
        /// </summary>
        /// <param name="idTipoCambio">Valor inicial de la propiedad idTipoCambio.</param>
        /// <param name="montoBs">Valor inicial de la propiedad montoBs.</param>
        /// <param name="oficial">Valor inicial de la propiedad oficial.</param>
        public static TipoCambioDolar CreateTipoCambioDolar(global::System.Int32 idTipoCambio, global::System.Decimal montoBs, global::System.String oficial)
        {
            TipoCambioDolar tipoCambioDolar = new TipoCambioDolar();
            tipoCambioDolar.idTipoCambio = idTipoCambio;
            tipoCambioDolar.montoBs = montoBs;
            tipoCambioDolar.oficial = oficial;
            return tipoCambioDolar;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoCambio
        {
            get
            {
                return _idTipoCambio;
            }
            set
            {
                if (_idTipoCambio != value)
                {
                    OnidTipoCambioChanging(value);
                    ReportPropertyChanging("idTipoCambio");
                    _idTipoCambio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTipoCambio");
                    OnidTipoCambioChanged();
                }
            }
        }
        private global::System.Int32 _idTipoCambio;
        partial void OnidTipoCambioChanging(global::System.Int32 value);
        partial void OnidTipoCambioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal montoBs
        {
            get
            {
                return _montoBs;
            }
            set
            {
                OnmontoBsChanging(value);
                ReportPropertyChanging("montoBs");
                _montoBs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("montoBs");
                OnmontoBsChanged();
            }
        }
        private global::System.Decimal _montoBs;
        partial void OnmontoBsChanging(global::System.Decimal value);
        partial void OnmontoBsChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String oficial
        {
            get
            {
                return _oficial;
            }
            set
            {
                OnoficialChanging(value);
                ReportPropertyChanging("oficial");
                _oficial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("oficial");
                OnoficialChanged();
            }
        }
        private global::System.String _oficial;
        partial void OnoficialChanging(global::System.String value);
        partial void OnoficialChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbCajaModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="idUsuario">Valor inicial de la propiedad idUsuario.</param>
        /// <param name="nombreusuario">Valor inicial de la propiedad nombreusuario.</param>
        /// <param name="contrasena">Valor inicial de la propiedad contrasena.</param>
        /// <param name="persona">Valor inicial de la propiedad persona.</param>
        public static Usuario CreateUsuario(global::System.Int32 idUsuario, global::System.String nombreusuario, global::System.String contrasena, global::System.Int32 persona)
        {
            Usuario usuario = new Usuario();
            usuario.idUsuario = idUsuario;
            usuario.nombreusuario = nombreusuario;
            usuario.contrasena = contrasena;
            usuario.persona = persona;
            return usuario;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idUsuario
        {
            get
            {
                return _idUsuario;
            }
            set
            {
                if (_idUsuario != value)
                {
                    OnidUsuarioChanging(value);
                    ReportPropertyChanging("idUsuario");
                    _idUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idUsuario");
                    OnidUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _idUsuario;
        partial void OnidUsuarioChanging(global::System.Int32 value);
        partial void OnidUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreusuario
        {
            get
            {
                return _nombreusuario;
            }
            set
            {
                OnnombreusuarioChanging(value);
                ReportPropertyChanging("nombreusuario");
                _nombreusuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreusuario");
                OnnombreusuarioChanged();
            }
        }
        private global::System.String _nombreusuario;
        partial void OnnombreusuarioChanging(global::System.String value);
        partial void OnnombreusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasena
        {
            get
            {
                return _contrasena;
            }
            set
            {
                OncontrasenaChanging(value);
                ReportPropertyChanging("contrasena");
                _contrasena = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasena");
                OncontrasenaChanged();
            }
        }
        private global::System.String _contrasena;
        partial void OncontrasenaChanging(global::System.String value);
        partial void OncontrasenaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 persona
        {
            get
            {
                return _persona;
            }
            set
            {
                OnpersonaChanging(value);
                ReportPropertyChanging("persona");
                _persona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("persona");
                OnpersonaChanged();
            }
        }
        private global::System.Int32 _persona;
        partial void OnpersonaChanging(global::System.Int32 value);
        partial void OnpersonaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_Caja_Usuarios", "Caja")]
        public EntityCollection<Caja> Cajas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Caja>("dbCajaModel.FK_Caja_Usuarios", "Caja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Caja>("dbCajaModel.FK_Caja_Usuarios", "Caja", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbCajaModel", "FK_Usuarios_Personas", "Personas")]
        public Persona Persona1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("dbCajaModel.FK_Usuarios_Personas", "Personas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("dbCajaModel.FK_Usuarios_Personas", "Personas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persona> Persona1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("dbCajaModel.FK_Usuarios_Personas", "Personas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persona>("dbCajaModel.FK_Usuarios_Personas", "Personas", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
